//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerKingPOS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BurgerKingPOS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3377fabb_363c_4b2b_a770_f49892781796 {
            get {
                object obj = ResourceManager.GetObject("3377fabb-363c-4b2b-a770-f49892781796", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _369feab8_6e70_45af_837d_e88d23870a97 {
            get {
                object obj = ResourceManager.GetObject("369feab8-6e70-45af-837d-e88d23870a97", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _37f11675_d3db_47dc_bb37_e39fbb070d38 {
            get {
                object obj = ResourceManager.GetObject("37f11675-d3db-47dc-bb37-e39fbb070d38", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _42d230c9_113e_40c6_b68f_7d2f48a4b2d1 {
            get {
                object obj = ResourceManager.GetObject("42d230c9-113e-40c6-b68f-7d2f48a4b2d1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _42f7a1dd_c0a7_49b4_9ce3_716d865acbaf {
            get {
                object obj = ResourceManager.GetObject("42f7a1dd-c0a7-49b4-9ce3-716d865acbaf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _704ef098_4a26_482d_9c6a_a78fd0b1667d {
            get {
                object obj = ResourceManager.GetObject("704ef098-4a26-482d-9c6a-a78fd0b1667d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _73adf9cb_6df6_4a7d_bcd6_44214b68ef24 {
            get {
                object obj = ResourceManager.GetObject("73adf9cb-6df6-4a7d-bcd6-44214b68ef24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _80e61146_bab9_4cf2_8ac5_7715737ac1e6 {
            get {
                object obj = ResourceManager.GetObject("80e61146-bab9-4cf2-8ac5-7715737ac1e6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap b54698e6_6454_4a61_b628_dc940e8ffc6b {
            get {
                object obj = ResourceManager.GetObject("b54698e6-6454-4a61-b628-dc940e8ffc6b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bk_02 {
            get {
                object obj = ResourceManager.GetObject("bk-02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dd19e6d9d64d7bf4494f6f2929b19ba5_hamburger_bk_chicken_fries_burger_king_fast_food_restaurant__820_500 {
            get {
                object obj = ResourceManager.GetObject("dd19e6d9d64d7bf4494f6f2929b19ba5_hamburger-bk-chicken-fries-burger-king-fast-food" +
                        "-restaurant-_820-500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dd19e6d9d64d7bf4494f6f2929b19ba5_hamburger_bk_chicken_fries_burger_king_fast_food_restaurant__820_5001 {
            get {
                object obj = ResourceManager.GetObject("dd19e6d9d64d7bf4494f6f2929b19ba5_hamburger-bk-chicken-fries-burger-king-fast-food" +
                        "-restaurant-_820-5001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dribbbble_02_2x {
            get {
                object obj = ResourceManager.GetObject("dribbbble-02_2x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fc68df07_4cb8_4f55_969c_bd61ef4c2dbe {
            get {
                object obj = ResourceManager.GetObject("fc68df07-4cb8-4f55-969c-bd61ef4c2dbe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_brand_font_burger_king_logo_png_clip_art {
            get {
                object obj = ResourceManager.GetObject("logo-brand-font-burger-king-logo-png-clip-art", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screen_Shot_2015_07_15_at_9_29_44_AM {
            get {
                object obj = ResourceManager.GetObject("Screen+Shot+2015-07-15+at+9.29.44+AM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thumb_1112_0_0_0_0_auto {
            get {
                object obj = ResourceManager.GetObject("thumb_1112_0_0_0_0_auto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
